### ISSUE TITLE
Product edit doesn't work.

### ISSUE THREAD

**Issue by blueink-ao** [vickydevhub/laravel-inertia-react#1]
Hi. I'm new react. I run your project and it worked really great. 
I leaned alot. Thank you so much. May I ask question? In Edit page.
submit button doesn't work. and the page won't change. Could you take a look that please?

**Comment by vickydevhub** [comment]
Thanks for raising this issue, I've fixed the issue on the edit product.
You can take a pull and check now.

**Comment by blueink-ao** [comment]
Hi. Thank you very much! That was so quick!
Actually I had been finding solution myself but I couldn't haha.
This is my first time React and Laravel connection. I learned lots of things from your code.
This is really great! so amazing. Thank you! Have a good day.
